export enum Permission {
  MANAGE_ORDERS_IMPORT = 'MANAGE_ORDERS_IMPORT',
  MANAGE_ORDERS = 'MANAGE_ORDERS',
  MANAGE_PRODUCT_TYPES_AND_ATTRIBUTES = 'MANAGE_PRODUCT_TYPES_AND_ATTRIBUTES',
  MANAGE_PRODUCTS = 'MANAGE_PRODUCTS',
  MANAGE_WAREHOUSE = 'MANAGE_WAREHOUSE',
  MANAGE_STAFF = 'MANAGE_STAFF',
  MANAGE_CATEGORIES = 'MANAGE_CATEGORIES',
  MANAGE_STATISTIC = 'MANAGE_STATISTIC',
  MANAGE_SYNC_RECOMMENDATION = 'MANAGE_SYNC_RECOMMENDATION',
}
